do:
	cp ../lib/controller.js ../lib/.controller.js
	cp ../lib/crdt.js ../lib/.crdt.js

	node rewrite.js

undo:
	rm ../lib/controller.js ../lib/crdt.js
	mv ../lib/.controller.js ../lib/controller.js
	mv ../lib/.crdt.js ../lib/crdt.js